apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rm_ci-deployment
  namespace: fuze
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rm_ci
    spec:
      containers:
      - name: rm_ci
        image: 329054710135.dkr.ecr.eu-west-2.amazonaws.com/RM_CI:BUILDNUMBER
        ports:
        - containerPort: 8080
