apiVersion: v1
kind: Service
metadata:
  name: rm_ci
  labels:
    app: rm_ci
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: rm_ci
  selector:
    app: rm_ci
