version: '2'
services:
  rabbitMq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost
  client:
    image: some/image
    links:
      - rabbitMq